export const ALL_MOVIE_REQUEST = "ALL_MOVIE_REQUEST";
export const ALL_MOVIE_SUCCESS = "ALL_MOVIE_SUCCESS";
export const ALL_MOVIE_FAIL = "ALL_MOVIE_FAIL";

export const ADMIN_MOVIE_REQUEST = "ADMIN_MOVIE_REQUEST";
export const ADMIN_MOVIE_SUCCESS = "ADMIN_MOVIE_SUCCESS";
export const ADMIN_MOVIE_FAIL = "ADMIN_MOVIE_FAIL";

export const NEW_MOVIE_REQUEST = "NEW_MOVIE_REQUEST";
export const NEW_MOVIE_SUCCESS = "NEW_MOVIE_SUCCESS";
export const NEW_MOVIE_RESET = "NEW_MOVIE_RESET";
export const NEW_MOVIE_FAIL = "NEW_MOVIE_FAIL";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_RESET = "UPDATE_MOVIE_RESET";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
